
export const spritesTemplate = {
  filename: 'svg-sprite.mjs',
  getContents ({ options }: any) {
    const imports = Object.keys(options.sprites).map(sprite => `  "${sprite}": () => import("${options.outDir}/${sprite}.svg").then(r => r.default || r)`).join(',\n')
    return [
      '// Generated by @nuxtjs/svg-sprite',
      'export const sprites = {',
      imports,
      '}',
      'export const spriteClass = "";\n',
      'export const spriteClassPrefix = "";\n',
      `export const defaultSprite = "${options.defaultSprite}";\n`
    ].join('\n')
  }
}

export const iconsTemplate = {
  filename: 'svg-sprite-icons.mjs',
  getContents ({ options }: any) {
    const icons = Object.entries(options.sprites).flatMap(([name, values]) => {
      return (values as any[]).map(icon => `${name}/${icon.name}`)
    })

    return [
      '// Generated by @nuxtjs/svg-sprite',
      `export const icons = ${JSON.stringify(icons, null, 2)}\n`
    ].join('\n')
  }
}
