import { pascalCase } from './utils'

export const spritesTemplate = {
  filename: 'svg-sprite.mjs',
  getContents ({ options }: any) {
    const imports = Object.keys(options.sprites).map(sprite => `  "${sprite}": () => import("${options.outDir}/${sprite}.svg").then(r => r.default || r)`).join(',\n')
    return [
      '// Generated by @nuxtjs/svg-sprite',
      'export const sprites = {',
      imports,
      '}',
      'export const spriteClass = "";\n',
      'export const spriteClassPrefix = "";\n',
      `export const defaultSprite = "${options.defaultSprite}";\n`
    ].join('\n')
  }
}

export const iconsTemplate = {
  filename: 'svg-sprite-icons.mjs',
  getContents ({ options }: any) {
    const icons = Object.entries(options.sprites).flatMap(([name, values]) => {
      return (values as any[]).map(icon => `${name}/${icon.name}`)
    })

    return [
      '// Generated by @nuxtjs/svg-sprite',
      `export const icons = ${JSON.stringify(icons, null, 2)}\n`
    ].join('\n')
  }
}

export const iconCollectionTemplate = {
  filename: 'svg-sprite-icon-collection.mjs',
  getContents ({ options }: any) {
    const sprites = Object.entries(options.sprites).map(([name, values]) => {
      const icons = (values as any[]).map((icon) => {
        return `\t${pascalCase(icon.name)}: '${name}/${icon.name}',`
      })
      return [`export const ${pascalCase(name)} = {`, ...icons, '};\n']
    })
    return [
      '// Generated by @nuxtjs/svg-sprite',
      ...sprites.flat(2)
    ].join('\n')
  }
}
export const iconCollectionDefinitionsTemplate = {
  filename: 'types/svg-sprite-icon-collection.d.ts',
  getContents ({ options }: any) {
    const sprites = Object.entries(options.sprites).map(([name, values]) => {
      const icons = (values as any[]).map((icon) => {
        return `\t\treadonly ${pascalCase(icon.name)}: '${name}/${icon.name}',`
      })
      return [`\texport declare const ${pascalCase(name)}: {`, ...icons, '\t};\n']
    })
    return [
      '// Generated by @nuxtjs/svg-sprite',
      'declare module \'#sprite\' {',
      ...sprites.flat(2),
      '}'
    ].join('\n')
  }
}
