
export const spritesTemplate = {
  filename: 'svg-sprite.mjs',
  getContents ({ options }) {
    const imports = Object.keys(options.sprites).map(sprite => `  "${sprite}": () => import("${options.outDir}/${sprite}.svg").then(r => r.default || r)`).join(',\n')
    return [
      '// Generated by @nuxtjs/svg-sprite',
      'export const sprites = {',
      imports,
      '}',
      'export const spriteClass = "";\n',
      'export const spriteClassPrefix = "";\n',
      `export const defaultSprite = "${options.defaultSprite}";\n`
    ].join('\n')
  }
}

export const iconsTemplate = {
  filename: 'svg-sprite-icons.mjs',
  getContents ({ options }) {
    const imports = Object.keys(options.sprites).map(name => ({
      name,
      symbols: options.sprites[name].map(svg => ({
        name: svg.name,
        key: `${options.defaultSprite === name ? '' : `${name}/`}${svg.name}`
      }))
    }))
    return [
      '// Generated by @nuxtjs/svg-sprite',
      `export const icons = ${JSON.stringify(imports, null, 2)}\n`
    ].join('\n')
  }
}
